name: apply-infra
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
    paths:
      - 'infrastructure/**'
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/**'

env:
  REGION: ap-southeast-2
  TF_STATE_BUCKET: andres-tf-states

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "bucket=${{ env.TF_STATE_BUCKET }}" --backend-config "region=${{ env.REGION }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var-file="envs/prod.tfvars"

      - name: Terraform Plan
        if: github.event_name != 'pull_request'
        id: apply
        run: terraform apply -no-color -var-file="envs/prod.tfvars"
